version: 2

sources:
  - name: raw
    tables:
      - name: sales
        description: "Raw sales data loaded from MinIO"
        columns:
          - name: id
            description: "Primary key"
          - name: order_id
            description: "Order identifier"
          - name: customer_id
            description: "Customer identifier"
          - name: amount
            description: "Order amount"
          - name: created_at
            description: "Timestamp of the order"

models:
  - name: stg_sales
    description: "Staging model for sales CSV"
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: order_id
        tests:
          - not_null

  - name: sales_summary
    description: "Daily sales aggregates"
    columns:
      - name: day
        tests:
          - not_null
