version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: sales
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
    volumes:
      - miniodata:/data

  airflow:
    image: apache/airflow:2.7.1
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: 'gAAAAAB...'  # replace in prod
      AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: sales
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./ingest:/opt/ingest
      - ./dbt:/opt/dbt
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio

  dbt:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dbt
    volumes:
      - ./dbt:/app/dbt
    environment:
      DBT_PROFILES_DIR: /app/dbt
    depends_on:
      - postgres

  streamlit:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      DATABASE_URL: "postgresql://airflow:airflow@postgres:5432/sales"
    depends_on:
      - postgres

volumes:
  pgdata:
  miniodata:
