FROM python:3.11-slim
WORKDIR /app
RUN pip install --no-cache-dir streamlit sqlalchemy psycopg2-binary pandas
COPY streamlit /app/streamlit
WORKDIR /app/streamlit
EXPOSE 8501
ENTRYPOINT ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
